[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@solmate/=lib/solmate/",
    "@v4-core/=lib/v4-core/src/",
    "@forge-std/=lib/forge-std/src/"
]
via_ir = true
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 80
tab_width = 4

   
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
